version: '3.3'

services:
 #Spring Boot API
 forent:
  container_name: forent-app
  build:
   context: .
   dockerfile: Dockerfile
  image: forent-app:v1
  restart: on-failure
  networks:
   - forentnet
  ports:
   - "8090:8090"
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rentals
   SPRING_DATASOURCE_PASSWORD: password
   SPRING_DATASOURCE_USERNAME: forent_user
   #- authUrl=http://localhost:8080/auth
  depends_on:
   - mysql
   - keycloak
  links:
   - mysql:3306
   - keycloak:8080
  volumes:
   - ./data:/srv
  
 #Mysql
 mysql:
  container_name: forent-mysql
  command: --default-authentication-plugin=mysql_native_password
  build:
   context: .
   dockerfile: mysql/Dockerfile
  image: forent_mysql:latest
  networks:
   - forentnet
  ports:
   - "6033:3306"
  volumes:
   - my-db:/var/lib/mysql
   
 #Keycloak
 keycloak:
  container_name: forent-keycloak
  build:
   context: .
  image: jboss/keycloak:latest
  networks:
   - forentnet
  ports:
   - "8080:8080"
  environment:
   KEYCLOAK_USER: adminforent
   KEYCLOAK_PASSWORD: admin
   DB_VENDOR: MYSQL
   DB_ADDR: mysql
   DB_USER: forent_user
   DB_DATABASE: rentals
   DB_PASSWORD: password
 

networks:
 forentnet:
#  driver: bridge

volumes:
  my-db:
   driver: local

