version: '3.3'

services:
 #Spring Boot API
 forent:
  container_name: forent-app
  build:
   context: .
   dockerfile: Dockerfile
  image: forent-app:v1
  networks:
   - forentnet
  ports:
   - "8090:8090"
  environment:
   SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rentals
   SPRING_DATASOURCE_PASSWORD: password
   SPRING_DATASOURCE_USERNAME: root
   #- authUrl=http://localhost:8080/auth
  depends_on:
   - mysql
   
 #Mysql
 mysql:
  container_name: forent_mysql
  build:
   context: .
   dockerfile: mysql/Dockerfile
  networks:
   - forentnet
  ports:
   - "6033:3306"


 #Keycloak
 #keycloak:
  #networks:
   #- forentnet
  #ports:
   #- '8080:8080'
  #restart: always
 
networks:
 forentnet:
  driver: bridge
