pipeline{
 	agent any
 	
 	stages{
		stage("Checkout Stage") {
			steps{
				git branch: 'feature1', url: 'https://github.com/DevQui/Forent'
			}
		}
		
		stage("Compile Stage") {
			steps{
				withMaven(maven: 'maven_3_6_3'){
					sh 'mvn clean compile -DskipTests=true'
				}
			}
		}
		
		stage("Unit Testing"){
            steps{
                withMaven(maven : 'maven_3_6_3'){
                    sh 'mvn clean test jacoco:report'
                    //sleep time: 1, unit: 'MINUTES'
                }
            }
            post{
                success{
                   publishHTML(target: [
                       allowMissing:false,
                       alwaysLinkToLastBuild: false,
                       keepAll: true,
                       reportDir: 'target/site/jacoco',
                       reportFiles: 'index.html',
                       reportName: 'Jacoco Report'
                    ])
                }
            }
        }
        
        stage("Build .jar file Stage") {
			steps{
				withMaven(maven: 'maven_3_6_3'){
				    sh 'mvn package'
				    stash includes: 'target/*.jar', name: 'targetfiles'
				}
			}
		}
        
        stage("Build and start docker-compose") {
            steps {
                script{
                    unstash 'targetfiles'
                    sh "docker-compose up --build"
                }
                //sleep time: 1, unit: 'MINUTES'
            }
        }

	}
}
